## Complete RO physical lock exported from the accepted routed ML-KEM RC1.
## Source DCP SHA-256: f843e5fa2daa7e0f5c14f776e34166618479dcb33c4e1d1293f7ca4145d401af
## Source bitstream SHA-256: 183e0af367376ebd7ca6bc2f3747314fd0602306a630af2a2e51858ef1f20e8e
## Vivado 2020.1 build 2902540; part xc7z020clg400-2.
## BEL is applied before LOC. Every connected leaf cell is fixed before routes.
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/clk_BUFG_inst_i_2"}]
set_property LOC SLICE_X113Y32 [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/clk_BUFG_inst_i_2"}]
set_property LOCK_PINS {I0:A2 I1:A6 I2:A1 I3:A3 I4:A5 I5:A4} [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/clk_BUFG_inst_i_2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/clk_BUFG_inst_i_2"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/clk_BUFG_inst_i_3"}]
set_property LOC SLICE_X113Y28 [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/clk_BUFG_inst_i_3"}]
set_property LOCK_PINS {I0:A4 I1:A6 I2:A3 I3:A5 I4:A1 I5:A2} [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/clk_BUFG_inst_i_3"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/clk_BUFG_inst_i_3"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/clk_BUFG_inst_i_4"}]
set_property LOC SLICE_X111Y33 [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/clk_BUFG_inst_i_4"}]
set_property LOCK_PINS {I0:A6 I1:A2 I2:A3 I3:A5 I4:A1 I5:A4} [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/clk_BUFG_inst_i_4"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/clk_BUFG_inst_i_4"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/clk_BUFG_inst_i_5"}]
set_property LOC SLICE_X111Y29 [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/clk_BUFG_inst_i_5"}]
set_property LOCK_PINS {I0:A5 I1:A2 I2:A4 I3:A3 I4:A1 I5:A6} [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/clk_BUFG_inst_i_5"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/clk_BUFG_inst_i_5"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/n_0_45840_BUFG_inst_i_2"}]
set_property LOC SLICE_X111Y25 [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/n_0_45840_BUFG_inst_i_2"}]
set_property LOCK_PINS {I0:A6 I1:A2 I2:A3 I3:A4 I4:A1 I5:A5} [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/n_0_45840_BUFG_inst_i_2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/n_0_45840_BUFG_inst_i_2"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/n_0_45840_BUFG_inst_i_3"}]
set_property LOC SLICE_X113Y24 [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/n_0_45840_BUFG_inst_i_3"}]
set_property LOCK_PINS {I0:A6 I1:A3 I2:A5 I3:A2 I4:A4 I5:A1} [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/n_0_45840_BUFG_inst_i_3"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/n_0_45840_BUFG_inst_i_3"}]
set_property BEL SLICEM.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/n_0_45840_BUFG_inst_i_4"}]
set_property LOC SLICE_X112Y26 [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/n_0_45840_BUFG_inst_i_4"}]
set_property LOCK_PINS {I0:A6 I1:A3 I2:A4 I3:A2 I4:A5 I5:A1} [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/n_0_45840_BUFG_inst_i_4"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/n_0_45840_BUFG_inst_i_4"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/n_0_45840_BUFG_inst_i_5"}]
set_property LOC SLICE_X109Y27 [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/n_0_45840_BUFG_inst_i_5"}]
set_property LOCK_PINS {I0:A6 I1:A1 I2:A3 I3:A4 I4:A2 I5:A5} [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/n_0_45840_BUFG_inst_i_5"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/lfsr_inst/n_0_45840_BUFG_inst_i_5"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[0].ro0/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X110Y27 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[0].ro0/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[0].ro0/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[0].ro0/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X110Y28 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[0].ro0/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[0].ro0/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[0].ro0/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X111Y28 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[0].ro0/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[0].ro0/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[0].ro0/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X110Y27 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[0].ro0/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[0].ro0/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[1].ro0/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X113Y29 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[1].ro0/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[1].ro0/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[1].ro0/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X111Y29 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[1].ro0/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[1].ro0/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[1].ro0/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X111Y29 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[1].ro0/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[1].ro0/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[1].ro0/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X113Y29 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[1].ro0/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[1].ro0/u_backend/LUT6_NAND0"}]
set_property BEL SLICEM.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[2].ro0/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X112Y32 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[2].ro0/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[2].ro0/u_backend/LUT6_INV0"}]
set_property BEL SLICEM.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[2].ro0/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X112Y32 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[2].ro0/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[2].ro0/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[2].ro0/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X113Y32 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[2].ro0/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[2].ro0/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[2].ro0/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X113Y32 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[2].ro0/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[2].ro0/u_backend/LUT6_NAND0"}]
set_property BEL SLICEM.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[3].ro0/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X112Y29 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[3].ro0/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[3].ro0/u_backend/LUT6_INV0"}]
set_property BEL SLICEM.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[3].ro0/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X112Y29 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[3].ro0/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[3].ro0/u_backend/LUT6_INV1"}]
set_property BEL SLICEM.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[3].ro0/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X112Y29 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[3].ro0/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[3].ro0/u_backend/LUT6_INV2"}]
set_property BEL SLICEM.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[3].ro0/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X112Y29 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[3].ro0/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[3].ro0/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[4].ro0/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X110Y35 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[4].ro0/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[4].ro0/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[4].ro0/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X110Y34 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[4].ro0/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[4].ro0/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[4].ro0/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X110Y34 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[4].ro0/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[4].ro0/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[4].ro0/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X110Y35 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[4].ro0/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[4].ro0/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[5].ro0/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X110Y29 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[5].ro0/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[5].ro0/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[5].ro0/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X110Y29 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[5].ro0/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[5].ro0/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[5].ro0/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X111Y29 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[5].ro0/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[5].ro0/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[5].ro0/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X110Y29 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[5].ro0/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[5].ro0/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[6].ro0/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X113Y31 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[6].ro0/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[6].ro0/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[6].ro0/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X113Y31 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[6].ro0/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[6].ro0/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[6].ro0/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X113Y31 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[6].ro0/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[6].ro0/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[6].ro0/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X113Y31 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[6].ro0/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[6].ro0/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[7].ro0/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X113Y28 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[7].ro0/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[7].ro0/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[7].ro0/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X113Y29 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[7].ro0/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[7].ro0/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[7].ro0/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X113Y28 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[7].ro0/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[7].ro0/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[7].ro0/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X113Y28 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[7].ro0/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[7].ro0/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[8].ro0/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X111Y35 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[8].ro0/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[8].ro0/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[8].ro0/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X110Y35 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[8].ro0/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[8].ro0/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[8].ro0/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X110Y35 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[8].ro0/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[8].ro0/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[8].ro0/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X111Y33 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[8].ro0/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[8].ro0/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[9].ro0/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X111Y28 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[9].ro0/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[9].ro0/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[9].ro0/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X111Y28 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[9].ro0/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[9].ro0/u_backend/LUT6_INV1"}]
set_property BEL SLICEM.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[9].ro0/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X112Y28 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[9].ro0/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[9].ro0/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[9].ro0/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X111Y28 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[9].ro0/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[9].ro0/u_backend/LUT6_NAND0"}]
set_property BEL SLICEM.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[10].ro0/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X112Y31 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[10].ro0/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[10].ro0/u_backend/LUT6_INV0"}]
set_property BEL SLICEM.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[10].ro0/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X112Y31 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[10].ro0/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[10].ro0/u_backend/LUT6_INV1"}]
set_property BEL SLICEM.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[10].ro0/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X112Y32 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[10].ro0/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[10].ro0/u_backend/LUT6_INV2"}]
set_property BEL SLICEM.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[10].ro0/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X112Y32 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[10].ro0/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[10].ro0/u_backend/LUT6_NAND0"}]
set_property BEL SLICEM.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[11].ro0/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X112Y27 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[11].ro0/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[11].ro0/u_backend/LUT6_INV0"}]
set_property BEL SLICEM.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[11].ro0/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X112Y27 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[11].ro0/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[11].ro0/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[11].ro0/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X113Y27 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[11].ro0/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[11].ro0/u_backend/LUT6_INV2"}]
set_property BEL SLICEM.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[11].ro0/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X112Y27 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[11].ro0/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[11].ro0/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[12].ro0/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X113Y30 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[12].ro0/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[12].ro0/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[12].ro0/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X113Y30 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[12].ro0/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[12].ro0/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[12].ro0/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X113Y30 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[12].ro0/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[12].ro0/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[12].ro0/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X113Y30 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[12].ro0/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[12].ro0/u_backend/LUT6_NAND0"}]
set_property BEL SLICEM.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[13].ro0/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X112Y27 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[13].ro0/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[13].ro0/u_backend/LUT6_INV0"}]
set_property BEL SLICEM.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[13].ro0/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X112Y28 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[13].ro0/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[13].ro0/u_backend/LUT6_INV1"}]
set_property BEL SLICEM.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[13].ro0/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X112Y28 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[13].ro0/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[13].ro0/u_backend/LUT6_INV2"}]
set_property BEL SLICEM.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[13].ro0/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X112Y28 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[13].ro0/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[13].ro0/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[14].ro0/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X113Y36 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[14].ro0/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[14].ro0/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[14].ro0/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X111Y35 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[14].ro0/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[14].ro0/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[14].ro0/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X111Y35 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[14].ro0/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[14].ro0/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[14].ro0/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X113Y36 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[14].ro0/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[14].ro0/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[15].ro0/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X113Y27 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[15].ro0/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[15].ro0/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[15].ro0/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X113Y27 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[15].ro0/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[15].ro0/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[15].ro0/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X113Y27 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[15].ro0/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[15].ro0/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring0[15].ro0/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X113Y29 [get_cells -hierarchical -filter {NAME == "u_puf/ring0[15].ro0/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring0[15].ro0/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[0].ro1/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X113Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[0].ro1/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[0].ro1/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[0].ro1/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X113Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[0].ro1/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[0].ro1/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[0].ro1/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X113Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[0].ro1/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[0].ro1/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[0].ro1/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X113Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[0].ro1/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[0].ro1/u_backend/LUT6_NAND0"}]
set_property BEL SLICEM.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[1].ro1/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X108Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[1].ro1/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[1].ro1/u_backend/LUT6_INV0"}]
set_property BEL SLICEM.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[1].ro1/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X108Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[1].ro1/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[1].ro1/u_backend/LUT6_INV1"}]
set_property BEL SLICEM.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[1].ro1/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X108Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[1].ro1/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[1].ro1/u_backend/LUT6_INV2"}]
set_property BEL SLICEM.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[1].ro1/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X108Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[1].ro1/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[1].ro1/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[2].ro1/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X113Y22 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[2].ro1/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[2].ro1/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[2].ro1/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X113Y22 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[2].ro1/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[2].ro1/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[2].ro1/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X113Y22 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[2].ro1/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[2].ro1/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[2].ro1/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X113Y22 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[2].ro1/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[2].ro1/u_backend/LUT6_NAND0"}]
set_property BEL SLICEM.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[3].ro1/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X112Y24 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[3].ro1/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[3].ro1/u_backend/LUT6_INV0"}]
set_property BEL SLICEM.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[3].ro1/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X112Y24 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[3].ro1/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[3].ro1/u_backend/LUT6_INV1"}]
set_property BEL SLICEM.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[3].ro1/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X112Y24 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[3].ro1/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[3].ro1/u_backend/LUT6_INV2"}]
set_property BEL SLICEM.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[3].ro1/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X112Y24 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[3].ro1/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[3].ro1/u_backend/LUT6_NAND0"}]
set_property BEL SLICEM.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[4].ro1/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X112Y25 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[4].ro1/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[4].ro1/u_backend/LUT6_INV0"}]
set_property BEL SLICEM.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[4].ro1/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X112Y25 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[4].ro1/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[4].ro1/u_backend/LUT6_INV1"}]
set_property BEL SLICEM.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[4].ro1/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X112Y25 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[4].ro1/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[4].ro1/u_backend/LUT6_INV2"}]
set_property BEL SLICEM.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[4].ro1/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X112Y25 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[4].ro1/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[4].ro1/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[5].ro1/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X111Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[5].ro1/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[5].ro1/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[5].ro1/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X111Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[5].ro1/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[5].ro1/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[5].ro1/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X111Y27 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[5].ro1/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[5].ro1/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[5].ro1/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X111Y27 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[5].ro1/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[5].ro1/u_backend/LUT6_NAND0"}]
set_property BEL SLICEM.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[6].ro1/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X112Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[6].ro1/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[6].ro1/u_backend/LUT6_INV0"}]
set_property BEL SLICEM.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[6].ro1/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X112Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[6].ro1/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[6].ro1/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[6].ro1/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X111Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[6].ro1/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[6].ro1/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[6].ro1/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X111Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[6].ro1/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[6].ro1/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[7].ro1/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X113Y24 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[7].ro1/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[7].ro1/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[7].ro1/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X113Y24 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[7].ro1/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[7].ro1/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[7].ro1/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X111Y23 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[7].ro1/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[7].ro1/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[7].ro1/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X113Y24 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[7].ro1/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[7].ro1/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[8].ro1/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X110Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[8].ro1/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[8].ro1/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[8].ro1/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X110Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[8].ro1/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[8].ro1/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[8].ro1/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X110Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[8].ro1/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[8].ro1/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[8].ro1/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X110Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[8].ro1/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[8].ro1/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[9].ro1/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X109Y27 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[9].ro1/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[9].ro1/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[9].ro1/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X109Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[9].ro1/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[9].ro1/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[9].ro1/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X109Y26 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[9].ro1/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[9].ro1/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[9].ro1/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X109Y27 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[9].ro1/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[9].ro1/u_backend/LUT6_NAND0"}]
set_property BEL SLICEM.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[10].ro1/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X112Y23 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[10].ro1/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[10].ro1/u_backend/LUT6_INV0"}]
set_property BEL SLICEM.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[10].ro1/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X112Y23 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[10].ro1/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[10].ro1/u_backend/LUT6_INV1"}]
set_property BEL SLICEM.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[10].ro1/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X112Y23 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[10].ro1/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[10].ro1/u_backend/LUT6_INV2"}]
set_property BEL SLICEM.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[10].ro1/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X112Y23 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[10].ro1/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[10].ro1/u_backend/LUT6_NAND0"}]
set_property BEL SLICEM.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[11].ro1/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X112Y22 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[11].ro1/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[11].ro1/u_backend/LUT6_INV0"}]
set_property BEL SLICEM.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[11].ro1/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X112Y22 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[11].ro1/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[11].ro1/u_backend/LUT6_INV1"}]
set_property BEL SLICEM.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[11].ro1/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X112Y22 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[11].ro1/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[11].ro1/u_backend/LUT6_INV2"}]
set_property BEL SLICEM.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[11].ro1/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X112Y22 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[11].ro1/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[11].ro1/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[12].ro1/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X113Y25 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[12].ro1/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[12].ro1/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[12].ro1/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X113Y25 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[12].ro1/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[12].ro1/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[12].ro1/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X113Y25 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[12].ro1/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[12].ro1/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[12].ro1/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X113Y25 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[12].ro1/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[12].ro1/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[13].ro1/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X111Y27 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[13].ro1/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[13].ro1/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[13].ro1/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X110Y27 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[13].ro1/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[13].ro1/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[13].ro1/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X110Y27 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[13].ro1/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[13].ro1/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[13].ro1/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X111Y27 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[13].ro1/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[13].ro1/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[14].ro1/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X111Y24 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[14].ro1/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[14].ro1/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[14].ro1/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X111Y25 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[14].ro1/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[14].ro1/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[14].ro1/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X111Y25 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[14].ro1/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[14].ro1/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[14].ro1/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X111Y24 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[14].ro1/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[14].ro1/u_backend/LUT6_NAND0"}]
set_property BEL SLICEL.A6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[15].ro1/u_backend/LUT6_INV0"}]
set_property LOC SLICE_X113Y23 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[15].ro1/u_backend/LUT6_INV0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[15].ro1/u_backend/LUT6_INV0"}]
set_property BEL SLICEL.B6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[15].ro1/u_backend/LUT6_INV1"}]
set_property LOC SLICE_X113Y23 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[15].ro1/u_backend/LUT6_INV1"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[15].ro1/u_backend/LUT6_INV1"}]
set_property BEL SLICEL.C6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[15].ro1/u_backend/LUT6_INV2"}]
set_property LOC SLICE_X113Y23 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[15].ro1/u_backend/LUT6_INV2"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[15].ro1/u_backend/LUT6_INV2"}]
set_property BEL SLICEL.D6LUT [get_cells -hierarchical -filter {NAME == "u_puf/ring1[15].ro1/u_backend/LUT6_NAND0"}]
set_property LOC SLICE_X113Y23 [get_cells -hierarchical -filter {NAME == "u_puf/ring1[15].ro1/u_backend/LUT6_NAND0"}]
set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME == "u_puf/ring1[15].ro1/u_backend/LUT6_NAND0"}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 SE2BEG1 NR1BEG1 WR1BEG2 IMUX_L4 CLBLL_LL_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[0].ro0/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[0].ro0/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LL_AMUX CLBLL_LOGIC_OUTS20 NR1BEG2 IMUX_L4 CLBLL_LL_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[0].ro0/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[0].ro0/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 NL1BEG_N3 IMUX_L5 CLBLL_L_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[0].ro0/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[0].ro0/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10 IMUX13 CLBLM_L_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[1].ro0/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[1].ro0/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 WR1BEG2 IMUX_L13 CLBLL_L_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[1].ro0/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[1].ro0/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9 IMUX_L34 CLBLL_L_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[1].ro0/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[1].ro0/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10 FAN_ALT5 FAN_BOUNCE5 IMUX35 CLBLM_M_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[2].ro0/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[2].ro0/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 NE2BEG2 SL1BEG2 WL1BEG1 IMUX43 CLBLM_M_D6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[2].ro0/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[2].ro0/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_M_D CLBLM_LOGIC_OUTS15 FAN_ALT3 FAN_BOUNCE3 IMUX13 CLBLM_L_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[2].ro0/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[2].ro0/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_M_D CLBLM_LOGIC_OUTS15 SR1BEG_S0 BYP_ALT4 BYP_BOUNCE4 IMUX4 CLBLM_M_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[3].ro0/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[3].ro0/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 BYP_ALT0 BYP_BOUNCE0 IMUX12 CLBLM_M_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[3].ro0/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[3].ro0/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 IMUX35 CLBLM_M_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[3].ro0/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[3].ro0/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 EE2BEG1 EE4BEG1 WR1BEG2 IMUX_L4 CLBLL_LL_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[4].ro0/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[4].ro0/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 SR1BEG1 IMUX_L12 CLBLL_LL_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[4].ro0/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[4].ro0/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 IMUX_L35 CLBLL_LL_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[4].ro0/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[4].ro0/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14 IMUX_L4 CLBLL_LL_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[5].ro0/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[5].ro0/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 BYP_ALT0 BYP_BOUNCE0 IMUX_L12 CLBLL_LL_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[5].ro0/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[5].ro0/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 NN2BEG1 SR1BEG1 SL1BEG1 IMUX_L42 CLBLL_L_D6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[5].ro0/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[5].ro0/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 SR1BEG_S0 BYP_ALT1 BYP_BOUNCE1 IMUX5 CLBLM_L_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[6].ro0/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[6].ro0/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 NL1BEG_N3 IMUX13 CLBLM_L_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[6].ro0/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[6].ro0/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 IMUX34 CLBLM_L_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[6].ro0/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[6].ro0/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 NE2BEG3 SL1BEG3 WL1BEG2 IMUX13 CLBLM_L_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[7].ro0/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[7].ro0/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 NR1BEG1 IMUX42 CLBLM_L_D6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[7].ro0/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[7].ro0/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 SL1BEG3 SR1BEG_S0 IMUX34 CLBLM_L_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[7].ro0/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[7].ro0/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10 NL1BEG1 NR1BEG1 IMUX_L34 CLBLL_L_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[8].ro0/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[8].ro0/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10 FAN_ALT5 FAN_BOUNCE5 IMUX_L35 CLBLL_LL_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[8].ro0/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[8].ro0/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14 NE2BEG2 SL1BEG2 WL1BEG1 IMUX_L43 CLBLL_LL_D6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[8].ro0/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[8].ro0/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLL_L_D CLBLL_LOGIC_OUTS11 SR1BEG_S0 BYP_ALT1 BYP_BOUNCE1 IMUX_L13 CLBLL_L_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[9].ro0/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[9].ro0/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9 IMUX_L34 CLBLL_L_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[9].ro0/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[9].ro0/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10 ER1BEG3 FAN_ALT3 FAN_BOUNCE3 IMUX43 CLBLM_M_D6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[9].ro0/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[9].ro0/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SL1BEG1 BYP_ALT4 BYP_BOUNCE4 IMUX12 CLBLM_M_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[10].ro0/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[10].ro0/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 IMUX35 CLBLM_M_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[10].ro0/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[10].ro0/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 EE4BEG2 NW2BEG2 IMUX4 CLBLM_M_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[10].ro0/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[10].ro0/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 IMUX4 CLBLM_M_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[11].ro0/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[11].ro0/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_M_AMUX CLBLM_LOGIC_OUTS20 IMUX12 CLBLM_M_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[11].ro0/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[11].ro0/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 BYP_ALT5 BYP_BOUNCE5 IMUX5 CLBLM_L_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[11].ro0/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[11].ro0/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 SR1BEG_S0 BYP_ALT1 BYP_BOUNCE1 IMUX5 CLBLM_L_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[12].ro0/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[12].ro0/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 NL1BEG_N3 IMUX13 CLBLM_L_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[12].ro0/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[12].ro0/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 IMUX34 CLBLM_L_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[12].ro0/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[12].ro0/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 SR1BEG3 FAN_ALT3 FAN_BOUNCE3 IMUX43 CLBLM_M_D6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[13].ro0/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[13].ro0/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_M_D CLBLM_LOGIC_OUTS15 NL1BEG2 IMUX4 CLBLM_M_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[13].ro0/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[13].ro0/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 BYP_ALT0 BYP_BOUNCE0 IMUX12 CLBLM_M_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[13].ro0/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[13].ro0/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 SR1BEG_S0 IMUX34 CLBLM_L_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[14].ro0/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[14].ro0/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10 SW2BEG2 IMUX_L5 CLBLL_L_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[14].ro0/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[14].ro0/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLL_L_A CLBLL_LOGIC_OUTS8 NL1BEG_N3 IMUX_L13 CLBLL_L_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[14].ro0/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[14].ro0/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 SR1BEG1 SR1BEG2 IMUX13 CLBLM_L_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[15].ro0/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[15].ro0/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 IMUX34 CLBLM_L_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[15].ro0/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[15].ro0/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10 SR1BEG3 BYP_ALT0 BYP_BOUNCE0 IMUX42 CLBLM_L_D6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring0[15].ro0/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring0[15].ro0/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 SR1BEG_S0 BYP_ALT1 BYP_BOUNCE1 IMUX5 CLBLM_L_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[0].ro1/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[0].ro1/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_L_AMUX CLBLM_LOGIC_OUTS16 IMUX13 CLBLM_L_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[0].ro1/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[0].ro1/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 IMUX34 CLBLM_L_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[0].ro1/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[0].ro1/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_M_D CLBLM_LOGIC_OUTS15 FAN_ALT3 FAN_BOUNCE3 FAN_ALT1 FAN_BOUNCE1 IMUX4 CLBLM_M_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[1].ro1/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[1].ro1/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_M_AMUX CLBLM_LOGIC_OUTS20 IMUX12 CLBLM_M_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[1].ro1/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[1].ro1/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 IMUX35 CLBLM_M_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[1].ro1/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[1].ro1/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 SR1BEG_S0 BYP_ALT1 BYP_BOUNCE1 IMUX5 CLBLM_L_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[2].ro1/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[2].ro1/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 NL1BEG_N3 IMUX13 CLBLM_L_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[2].ro1/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[2].ro1/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 IMUX34 CLBLM_L_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[2].ro1/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[2].ro1/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_M_D CLBLM_LOGIC_OUTS15 EE4BEG3 WL1BEG1 IMUX4 CLBLM_M_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[3].ro1/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[3].ro1/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 BYP_ALT0 BYP_BOUNCE0 IMUX12 CLBLM_M_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[3].ro1/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[3].ro1/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 IMUX35 CLBLM_M_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[3].ro1/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[3].ro1/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_M_D CLBLM_LOGIC_OUTS15 EE4BEG3 WL1BEG1 IMUX4 CLBLM_M_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[4].ro1/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[4].ro1/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 BYP_ALT0 BYP_BOUNCE0 IMUX12 CLBLM_M_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[4].ro1/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[4].ro1/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 IMUX35 CLBLM_M_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[4].ro1/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[4].ro1/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLL_L_D CLBLL_LOGIC_OUTS11 SE2BEG3 WL1BEG2 IMUX_L5 CLBLL_L_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[5].ro1/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[5].ro1/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLL_L_A CLBLL_LOGIC_OUTS8 NL1BEG_N3 IMUX_L13 CLBLL_L_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[5].ro1/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[5].ro1/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9 NR1BEG1 IMUX_L34 CLBLL_L_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[5].ro1/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[5].ro1/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLL_L_D CLBLL_LOGIC_OUTS11 EL1BEG2 IMUX12 CLBLM_M_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[6].ro1/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[6].ro1/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 IMUX35 CLBLM_M_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[6].ro1/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[6].ro1/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 WL1BEG1 IMUX_L34 CLBLL_L_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[6].ro1/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[6].ro1/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 SR1BEG_S0 BYP_ALT1 BYP_BOUNCE1 IMUX13 CLBLM_L_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[7].ro1/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[7].ro1/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 IMUX34 CLBLM_L_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[7].ro1/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[7].ro1/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10 SW2BEG2 IMUX_L5 CLBLL_L_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[7].ro1/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[7].ro1/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLL_LL_D CLBLL_LOGIC_OUTS15 SR1BEG_S0 BYP_ALT4 BYP_BOUNCE4 IMUX_L4 CLBLL_LL_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[8].ro1/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[8].ro1/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLL_LL_A CLBLL_LOGIC_OUTS12 BYP_ALT0 BYP_BOUNCE0 IMUX_L12 CLBLL_LL_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[8].ro1/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[8].ro1/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 IMUX_L35 CLBLL_LL_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[8].ro1/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[8].ro1/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 SR1BEG_S0 IMUX34 CLBLM_L_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[9].ro1/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[9].ro1/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10 SL1BEG2 IMUX5 CLBLM_L_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[9].ro1/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[9].ro1/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 NL1BEG_N3 IMUX13 CLBLM_L_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[9].ro1/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[9].ro1/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_M_D CLBLM_LOGIC_OUTS15 EE4BEG3 WL1BEG1 IMUX4 CLBLM_M_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[10].ro1/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[10].ro1/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 BYP_ALT0 BYP_BOUNCE0 IMUX12 CLBLM_M_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[10].ro1/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[10].ro1/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 IMUX35 CLBLM_M_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[10].ro1/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[10].ro1/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_M_D CLBLM_LOGIC_OUTS15 EE4BEG3 WL1BEG1 IMUX4 CLBLM_M_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[11].ro1/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[11].ro1/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12 BYP_ALT0 BYP_BOUNCE0 IMUX12 CLBLM_M_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[11].ro1/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[11].ro1/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 IMUX35 CLBLM_M_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[11].ro1/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[11].ro1/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 SR1BEG_S0 BYP_ALT1 BYP_BOUNCE1 IMUX5 CLBLM_L_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[12].ro1/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[12].ro1/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 NL1BEG_N3 IMUX13 CLBLM_L_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[12].ro1/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[12].ro1/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 IMUX34 CLBLM_L_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[12].ro1/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[12].ro1/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9 NL1BEG0 FAN_ALT3 FAN_BOUNCE3 IMUX_L5 CLBLL_L_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[13].ro1/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[13].ro1/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLL_L_A CLBLL_LOGIC_OUTS8 BYP_ALT1 BYP_BOUNCE1 IMUX_L35 CLBLL_LL_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[13].ro1/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[13].ro1/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14 NE2BEG2 SL1BEG2 WL1BEG1 IMUX_L43 CLBLL_LL_D6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[13].ro1/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[13].ro1/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9 BYP_ALT4 BYP_BOUNCE4 BYP_ALT5 BYP_BOUNCE5 IMUX_L5 CLBLL_L_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[14].ro1/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[14].ro1/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLL_L_A CLBLL_LOGIC_OUTS8 NR1BEG0 NL1BEG_N3 IMUX_L13 CLBLL_L_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[14].ro1/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[14].ro1/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9 IMUX_L34 CLBLL_L_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[14].ro1/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[14].ro1/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_LOGIC_OUTS11 SR1BEG_S0 BYP_ALT1 BYP_BOUNCE1 IMUX5 CLBLM_L_A6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[15].ro1/u_backend/t0"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[15].ro1/u_backend/t0"}]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8 NL1BEG_N3 IMUX13 CLBLM_L_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[15].ro1/u_backend/t1"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[15].ro1/u_backend/t1"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 IMUX34 CLBLM_L_C6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ring1[15].ro1/u_backend/t2"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ring1[15].ro1/u_backend/t2"}]
set_property FIXED_ROUTE { { CLBLL_L_A CLBLL_LOGIC_OUTS8  { SL1BEG0 IMUX_L24 CLBLL_LL_B5 }  NE6BEG0 NW2BEG0 WR1BEG1 IMUX_L26 CLBLL_L_B4 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[0]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[0]"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10  { IMUX_L5 CLBLL_L_A6 }  EE2BEG2 WR1BEG3 IMUX30 CLBLM_L_C5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[1]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[1]"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9  { IMUX10 CLBLM_L_A4 }  BYP_ALT4 BYP_BOUNCE4 IMUX30 CLBLM_L_C5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[2]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[2]"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { SE2BEG2 WL1BEG1 IMUX3 CLBLM_L_A2 }  BYP_ALT2 BYP_BOUNCE2 BYP_ALT3 BYP_BOUNCE3 IMUX47 CLBLM_M_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[3]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[3]"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { BYP_ALT2 BYP_BOUNCE2 IMUX_L24 CLBLL_LL_B5 }  SE2BEG2 WL1BEG1 IMUX_L19 CLBLL_L_B2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[4]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[4]"}]
set_property FIXED_ROUTE { { CLBLL_L_D CLBLL_LOGIC_OUTS11 SS2BEG3 NR1BEG3 NR1BEG3  { FAN_ALT3 FAN_BOUNCE3 IMUX_L3 CLBLL_L_A2 }  IMUX_L31 CLBLL_LL_C5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[5]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[5]"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10  { NR1BEG2 IMUX5 CLBLM_L_A6 }  SE2BEG2 NR1BEG2 WR1BEG3 IMUX46 CLBLM_L_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[6]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[6]"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10  { IMUX5 CLBLM_L_A6 }  SW2BEG2 ER1BEG3 NR1BEG3 IMUX46 CLBLM_L_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[7]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[7]"}]
set_property FIXED_ROUTE { { CLBLL_LL_D CLBLL_LOGIC_OUTS15  { SR1BEG_S0 SS2BEG0 IMUX_L25 CLBLL_L_B5 }  SS2BEG3 IMUX_L30 CLBLL_L_C5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[8]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[8]"}]
set_property FIXED_ROUTE { { CLBLM_M_D CLBLM_LOGIC_OUTS15  { WR1BEG_S0 IMUX_L0 CLBLL_L_A3 }  EE4BEG3 WW2BEG2 IMUX_L46 CLBLL_L_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[9]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[9]"}]
set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12  { IMUX0 CLBLM_L_A3 }  IMUX24 CLBLM_M_B5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[10]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[10]"}]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8  { NR1BEG0 IMUX9 CLBLM_L_A5 }  NL1BEG_N3 BYP_ALT3 BYP_BOUNCE3 IMUX31 CLBLM_M_C5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[11]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[11]"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10 NW2BEG2  { NN2BEG2 IMUX_L13 CLBLL_L_B6 }  SR1BEG2 ER1BEG3 IMUX46 CLBLM_L_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[12]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[12]"}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13  { NW2BEG1 IMUX_L9 CLBLL_L_A5 }  BYP_ALT5 BYP_BOUNCE5 IMUX31 CLBLM_M_C5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[13]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[13]"}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9  { SE2BEG1 SS2BEG1 IMUX3 CLBLM_L_A2 }  NL1BEG0 EL1BEG_N3 NR1BEG3 IMUX46 CLBLM_L_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[14]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[14]"}]
set_property FIXED_ROUTE { { CLBLM_L_D CLBLM_L_DMUX CLBLM_LOGIC_OUTS19  { NE2BEG1 NW2BEG1 IMUX9 CLBLM_L_A5 }  NR1BEG1 IMUX10 CLBLM_L_A4 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[15]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out0[15]"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10 EE4BEG2 WR1BEG3  { IMUX7 CLBLM_M_A1 }  IMUX46 CLBLM_L_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[0]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[0]"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 BYP_ALT2 BYP_BOUNCE2 BYP_ALT3 BYP_BOUNCE3  { IMUX25 CLBLM_L_B5 }  IMUX47 CLBLM_M_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[1]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[1]"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10 SW2BEG2 ER1BEG3 NR1BEG3  { NN2BEG3 WR1BEG_S0 IMUX_L9 CLBLL_L_A5 }  IMUX46 CLBLM_L_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[2]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[2]"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 BYP_ALT2 BYP_BOUNCE2  { IMUX6 CLBLM_L_A1 }  BYP_ALT3 BYP_BOUNCE3 IMUX47 CLBLM_M_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[3]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[3]"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 BYP_ALT2 BYP_BOUNCE2 BYP_ALT3 BYP_BOUNCE3  { IMUX1 CLBLM_M_A3 }  IMUX47 CLBLM_M_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[4]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[4]"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10  { WR1BEG3 IMUX14 CLBLM_L_B1 }  SE2BEG2 NR1BEG2 WR1BEG3 IMUX_L46 CLBLL_L_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[5]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[5]"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10 EE2BEG2 EE4BEG2  { SW2BEG1 IMUX_L3 CLBLL_L_A2 }  WR1BEG3 IMUX_L46 CLBLL_L_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[6]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[6]"}]
set_property FIXED_ROUTE { { CLBLL_L_A CLBLL_LOGIC_OUTS8 NE2BEG0  { IMUX0 CLBLM_L_A3 }  NL1BEG_N3 IMUX46 CLBLM_L_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[7]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[7]"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { EL1BEG1 IMUX2 CLBLM_M_A2 }  BYP_ALT2 BYP_BOUNCE2 BYP_ALT3 BYP_BOUNCE3 IMUX_L47 CLBLL_LL_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[8]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[8]"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 NR1BEG1  { IMUX26 CLBLM_L_B4 }  BYP_ALT4 BYP_BOUNCE4 IMUX46 CLBLM_L_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[9]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[9]"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NW2BEG2 NL1BEG1 IMUX_L10 CLBLL_L_A4 }  BYP_ALT2 BYP_BOUNCE2 BYP_ALT3 BYP_BOUNCE3 IMUX47 CLBLM_M_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[10]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[10]"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NL1BEG1 NR1BEG1 IMUX3 CLBLM_L_A2 }  BYP_ALT2 BYP_BOUNCE2 BYP_ALT3 BYP_BOUNCE3 IMUX47 CLBLM_M_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[11]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[11]"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10 EE4BEG2 WR1BEG3  { NL1BEG2 IMUX4 CLBLM_M_A6 }  IMUX46 CLBLM_L_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[12]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[12]"}]
set_property FIXED_ROUTE { { CLBLL_LL_D CLBLL_LOGIC_OUTS15  { SR1BEG_S0 IMUX_L25 CLBLL_L_B5 }  WL1BEG2 IMUX13 CLBLM_L_B6 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[13]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[13]"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10  { IMUX_L5 CLBLL_L_A6 }  SL1BEG2 FAN_ALT5 FAN_BOUNCE5 IMUX_L25 CLBLL_L_B5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[14]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[14]"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10  { NR1BEG2 IMUX5 CLBLM_L_A6 }  SW2BEG2 ER1BEG3 NR1BEG3 IMUX46 CLBLM_L_D5 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[15]"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro_out1[15]"}]
