#!/usr/bin/env python3
"""Generate deterministic FIPS 202 regression vectors with Python hashlib.

The checked-in result lets the RTL test run without Python at simulation time.
Regenerate it explicitly whenever this script changes.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


MODES = (
    ("SHA3-512", 0, 72, 64),
    ("SHAKE256", 1, 136, None),
    ("SHAKE128", 2, 168, None),
    ("SHA3-256", 3, 136, 32),
)


def patterned_message(length: int) -> bytes:
    return bytes(((index * 17) + 3) & 0xFF for index in range(length))


def digest(mode: int, message: bytes, output_length: int) -> bytes:
    if mode == 0:
        return hashlib.sha3_512(message).digest()
    if mode == 1:
        return hashlib.shake_256(message).digest(output_length)
    if mode == 2:
        return hashlib.shake_128(message).digest(output_length)
    if mode == 3:
        return hashlib.sha3_256(message).digest()
    raise ValueError(f"unsupported mode {mode}")


def build_vectors() -> list[tuple[str, int, bytes, int, bytes]]:
    vectors: list[tuple[str, int, bytes, int, bytes]] = []

    for mode_name, mode, rate, fixed_output_length in MODES:
        messages = (
            ("empty", b""),
            ("abc", b"abc"),
            ("rate_minus_1", patterned_message(rate - 1)),
            ("rate_exact", patterned_message(rate)),
            ("rate_plus_1", patterned_message(rate + 1)),
            ("two_rates_plus_17", patterned_message((2 * rate) + 17)),
        )

        if fixed_output_length is None:
            output_lengths = (32, 64, rate - 1, rate, rate + 13, (2 * rate) + 5)
        else:
            output_lengths = (fixed_output_length,) * len(messages)

        for (case_name, message), output_length in zip(messages, output_lengths):
            expected = digest(mode, message, output_length)
            vectors.append(
                (
                    f"{mode_name.lower()}_{case_name}",
                    mode,
                    message,
                    output_length,
                    expected,
                )
            )

        if fixed_output_length is None:
            vectors.append(
                (
                    f"{mode_name.lower()}_zero_output",
                    mode,
                    b"abc",
                    0,
                    b"",
                )
            )

    return vectors


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=Path("fips202_vectors.txt"))
    args = parser.parse_args()

    lines = [
        "# Deterministic FIPS 202 regression vectors generated by Python hashlib",
        "# name|mode|message_hex (- means empty)|output_bytes|expected_hex (- means empty)",
    ]
    for name, mode, message, output_length, expected in build_vectors():
        message_hex = message.hex() if message else "-"
        expected_hex = expected.hex() if expected else "-"
        lines.append(f"{name}|{mode}|{message_hex}|{output_length}|{expected_hex}")

    args.output.write_text("\n".join(lines) + "\n", encoding="ascii")


if __name__ == "__main__":
    main()
