#!/usr/bin/env python3
"""Rebuild the checked-in ML-KEM-512 Decaps/rejection vector corpus."""

import argparse
import ctypes
import hashlib
import json
from pathlib import Path


MUTATIONS = (
    (0, 0x01),
    (319, 0x80),
    (320, 0x01),
    (511, 0x80),
    (639, 0x80),
    (640, 0x01),
    (767, 0x80),
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--keygen-json", required=True)
    parser.add_argument("--encap-json", required=True)
    parser.add_argument("--reference-library", required=True)
    parser.add_argument("--output", default="mlkem512_decap_ref.txt")
    args = parser.parse_args()

    library = ctypes.CDLL(args.reference_library)
    byte_ptr = ctypes.POINTER(ctypes.c_uint8)
    keypair = library.pqcrystals_kyber512_ref_keypair_derand
    encaps = library.pqcrystals_kyber512_ref_enc_derand
    decaps = library.pqcrystals_kyber512_ref_dec
    for function in (keypair, encaps, decaps):
        function.argtypes = [byte_ptr, byte_ptr, byte_ptr]
        function.restype = ctypes.c_int

    keygen_document = json.loads(Path(args.keygen_json).read_text())
    encap_document = json.loads(Path(args.encap_json).read_text())
    keygen_tests = next(
        group["tests"]
        for group in keygen_document["testGroups"]
        if group["tgId"] == 1 and group["parameterSet"] == "ML-KEM-512"
    )
    encap_tests = next(
        group["tests"]
        for group in encap_document["testGroups"]
        if group["tgId"] == 1
        and group["parameterSet"] == "ML-KEM-512"
        and group["function"] == "encapsulation"
    )
    if len(keygen_tests) != 25 or len(encap_tests) != 25:
        raise ValueError("expected 25 KeyGen and 25 Encaps input vectors")

    lines = [
        "# 25 Decaps vectors generated by pq-crystals/kyber ref commit",
        "# 3edd5af5991927164edd4aacebfcbee00b8064e7; d/z from NIST KeyGen tgId 1",
        "# INVALID_J_<offset>_<mask> is SHAKE256(z || mutated-c, 32 bytes)",
    ]
    for keygen_test, encap_test in zip(keygen_tests, encap_tests):
        d = bytes.fromhex(keygen_test["d"])
        z = bytes.fromhex(keygen_test["z"])
        m = bytes.fromhex(encap_test["m"])
        coins = (ctypes.c_uint8 * 64).from_buffer_copy(d + z)
        public_key = (ctypes.c_uint8 * 800)()
        private_key = (ctypes.c_uint8 * 1632)()
        if keypair(public_key, private_key, coins) != 0:
            raise RuntimeError("reference KeyGen failed")
        if bytes(public_key).hex().upper() != keygen_test["ek"]:
            raise ValueError("reference ek differs from NIST")
        if bytes(private_key).hex().upper() != keygen_test["dk"]:
            raise ValueError("reference dk differs from NIST")

        ciphertext = (ctypes.c_uint8 * 768)()
        encaps_key = (ctypes.c_uint8 * 32)()
        message = (ctypes.c_uint8 * 32).from_buffer_copy(m)
        if encaps(ciphertext, encaps_key, public_key, message) != 0:
            raise RuntimeError("reference Encaps failed")
        decaps_key = (ctypes.c_uint8 * 32)()
        if decaps(decaps_key, ciphertext, private_key) != 0:
            raise RuntimeError("reference Decaps failed")
        if bytes(encaps_key) != bytes(decaps_key):
            raise ValueError("reference Encaps/Decaps key mismatch")

        lines.extend(
            [
                f"TCID={keygen_test['tcId']}",
                f"D={d.hex().upper()}",
                f"Z={z.hex().upper()}",
                f"M={m.hex().upper()}",
                f"C={bytes(ciphertext).hex().upper()}",
                f"K={bytes(encaps_key).hex().upper()}",
            ]
        )
        for offset, mask in MUTATIONS:
            invalid_ciphertext = bytearray(ciphertext)
            invalid_ciphertext[offset] ^= mask
            invalid_buffer = (ctypes.c_uint8 * 768).from_buffer_copy(
                invalid_ciphertext
            )
            rejection_key = (ctypes.c_uint8 * 32)()
            if decaps(rejection_key, invalid_buffer, private_key) != 0:
                raise RuntimeError("reference rejection path failed")
            rejection_oracle = hashlib.shake_256(
                z + invalid_ciphertext
            ).digest(32)
            if bytes(rejection_key) != rejection_oracle:
                raise ValueError(
                    "reference rejection key differs from SHAKE256"
                )
            lines.append(
                f"INVALID_J_{offset}_{mask:02X}="
                f"{rejection_oracle.hex().upper()}"
            )

    Path(args.output).write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
